In [1]:
#Using the smallgray.png file in the folder, following dimensions are created "manually"
[[123,12,123,12,123],[],[]] #5 numbers are added because there are 5 columns in the picture

[[123, 12, 123, 12, 123], [], []]

In [3]:
#Numpy can be used to organize this in a better format as array
import numpy
n=numpy.arange(27)

In [4]:
n #numpy arrange with one dimension

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
type(n) #shows that numpy can do upto 3 dimensions

numpy.ndarray

In [7]:
n.reshape(3,9) #numpy arranging with two dimensions

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [8]:
n.reshape(3,3,3) #numpy arranging with three dimensions array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
m=numpy.asarray([[123,12,123,12,123],[],[]]) #creating a new list and converting into numpy array

In [12]:
m

array([list([123, 12, 123, 12, 123]), list([]), list([])], dtype=object)

In [14]:
type(m)  #This is numpy array 

numpy.ndarray