In [2]:
import numpy
import cv2

In [3]:
#reading the image dimensions. 0 arg open as gray
im_g=cv2.imread("smallgray.png",0) 
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [4]:
#reading the image dimensions.1 arg open as BGR(Blue Green Red)
im_g=cv2.imread("smallgray.png",1) 
print(im_g)

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [5]:
#creates a new file based on numpy array
cv2.imwrite("newsmallgray.png",im_g) 

True

In [6]:
#indexing in numpy array
im_g[0:2]

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]]], dtype=uint8)

In [8]:
im_g[0:2,2:4]

array([[[104, 104, 104],
        [121, 121, 121]],

       [[255, 255, 255],
        [255, 255, 255]]], dtype=uint8)

In [9]:
#numpy array shape
im_g.shape

(3, 5, 3)

In [12]:
im_g[2,1]

array([134, 134, 134], dtype=uint8)

In [13]:
#iterating in numpy array by rows
for i in im_g:
    print(i)

[[187 187 187]
 [158 158 158]
 [104 104 104]
 [121 121 121]
 [143 143 143]]
[[198 198 198]
 [125 125 125]
 [255 255 255]
 [255 255 255]
 [147 147 147]]
[[209 209 209]
 [134 134 134]
 [255 255 255]
 [ 97  97  97]
 [182 182 182]]


In [14]:
#iterating in numpy array by columns
for i in im_g.T:
    print(i)

[[187 198 209]
 [158 125 134]
 [104 255 255]
 [121 255  97]
 [143 147 182]]
[[187 198 209]
 [158 125 134]
 [104 255 255]
 [121 255  97]
 [143 147 182]]
[[187 198 209]
 [158 125 134]
 [104 255 255]
 [121 255  97]
 [143 147 182]]


In [15]:
#iterating value by value
for i in im_g.flat:
    print(i)

187
187
187
158
158
158
104
104
104
121
121
121
143
143
143
198
198
198
125
125
125
255
255
255
255
255
255
147
147
147
209
209
209
134
134
134
255
255
255
97
97
97
182
182
182


In [16]:
#stacking and splitting numpy arrays
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [24]:
#stacking horizontally
ims=numpy.hstack((im_g,im_g,im_g)) 
print(ims)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]
  [187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]
  [187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]
  [198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]
  [198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]
  [209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]
  [209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [25]:
#splitting horizontally
lst=numpy.hsplit(ims,5)
lst

[array([[[187, 187, 187],
         [158, 158, 158],
         [104, 104, 104]],
 
        [[198, 198, 198],
         [125, 125, 125],
         [255, 255, 255]],
 
        [[209, 209, 209],
         [134, 134, 134],
         [255, 255, 255]]], dtype=uint8),
 array([[[121, 121, 121],
         [143, 143, 143],
         [187, 187, 187]],
 
        [[255, 255, 255],
         [147, 147, 147],
         [198, 198, 198]],
 
        [[ 97,  97,  97],
         [182, 182, 182],
         [209, 209, 209]]], dtype=uint8),
 array([[[158, 158, 158],
         [104, 104, 104],
         [121, 121, 121]],
 
        [[125, 125, 125],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[134, 134, 134],
         [255, 255, 255],
         [ 97,  97,  97]]], dtype=uint8),
 array([[[143, 143, 143],
         [187, 187, 187],
         [158, 158, 158]],
 
        [[147, 147, 147],
         [198, 198, 198],
         [125, 125, 125]],
 
        [[182, 182, 182],
         [209, 209, 209],
         [134, 134

In [29]:
#stacking vertically
ims=numpy.vstack((im_g,im_g,im_g)) 
print(ims)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]

 [[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]

 [[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [30]:
#splitting vertically
lst=numpy.vsplit(ims,3)
lst

[array([[[187, 187, 187],
         [158, 158, 158],
         [104, 104, 104],
         [121, 121, 121],
         [143, 143, 143]],
 
        [[198, 198, 198],
         [125, 125, 125],
         [255, 255, 255],
         [255, 255, 255],
         [147, 147, 147]],
 
        [[209, 209, 209],
         [134, 134, 134],
         [255, 255, 255],
         [ 97,  97,  97],
         [182, 182, 182]]], dtype=uint8),
 array([[[187, 187, 187],
         [158, 158, 158],
         [104, 104, 104],
         [121, 121, 121],
         [143, 143, 143]],
 
        [[198, 198, 198],
         [125, 125, 125],
         [255, 255, 255],
         [255, 255, 255],
         [147, 147, 147]],
 
        [[209, 209, 209],
         [134, 134, 134],
         [255, 255, 255],
         [ 97,  97,  97],
         [182, 182, 182]]], dtype=uint8),
 array([[[187, 187, 187],
         [158, 158, 158],
         [104, 104, 104],
         [121, 121, 121],
         [143, 143, 143]],
 
        [[198, 198, 198],
         [125, 12